services:
  # Backend Service
  - type: web
    name: construction-marketplace-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: yarn install --frozen-lockfile --no-emoji --no-progress --silent || yarn install --no-emoji --no-progress --silent
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      # Define your environment variables in the Render dashboard or add them here (avoid committing secrets):
      # - key: MONGO_URI
      #   sync: false
      # - key: CLOUDINARY_URL
      #   sync: false

  # Frontend Service
  - type: web
    name: construction-marketplace-1
    env: node
    rootDir: client
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://construction-marketplace.onrender.com
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: NODE_OPTIONS
        value: --max-old-space-size=400 --expose-gc
      - key: MEMORY_PRESSURE_CHECK
        value: 1
      - key: FORCE_COLOR
        value: 0
