services:
  - type: web
    name: construction-marketplace-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: yarn install --frozen-lockfile --no-emoji --no-progress --silent || yarn install --no-emoji --no-progress --silent
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      # Define your environment variables in the Render dashboard or add them here (avoid committing secrets):
      # - key: MONGO_URI
      #   sync: false
      # - key: CLOUDINARY_URL
      #   sync: false
