services:
  # Backend Service
  - type: web
    name: construction-marketplace
    env: node
    rootDir: server
    plan: free
    buildCommand: yarn install --frozen-lockfile --no-emoji --no-progress --silent || yarn install --no-emoji --no-progress --silent
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ALLOWED_ORIGINS
        value: https://construction-marketplace-1.onrender.com
      - key: ALLOW_ALL_ORIGINS
        value: true
      # Define your environment variables in the Render dashboard or add them here (avoid committing secrets):
      # - key: MONGO_URI
      #   sync: false
      # - key: CLOUDINARY_URL
      #   sync: false

  # Frontend Service
  - type: web
    name: construction-marketplace-1
    env: node
    rootDir: client
    plan: free
    buildCommand: npm ci --prefer-offline --no-audit --progress=false && NODE_OPTIONS='--max-old-space-size=1024' npm run build
    startCommand: node --max-old-space-size=400 --expose-gc server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://construction-marketplace.onrender.com
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: NODE_OPTIONS
        value: --max-old-space-size=400 --expose-gc
      - key: MEMORY_PRESSURE_CHECK
        value: 1
      - key: FORCE_COLOR
        value: 0
      - key: DISABLE_PRERENDERING
        value: 1
      - key: SKIP_ENV_VALIDATION
        value: 1
