services:
  # Backend Service
  - type: web
    name: construction-marketplace-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: yarn install --frozen-lockfile --no-emoji --no-progress --silent || yarn install --no-emoji --no-progress --silent
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      # Define your environment variables in the Render dashboard or add them here (avoid committing secrets):
      # - key: MONGO_URI
      #   sync: false
      # - key: CLOUDINARY_URL
      #   sync: false

  # Frontend Service
  - type: web
    name: construction-marketplace-frontend
    env: node
    rootDir: client
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://construction-marketpla.onrender.com
      # Add more environment variables as needed:
      # - key: NEXT_TELEMETRY_DISABLED
      #   value: 1
