services:
  # Backend Service - Enhanced for Production Stability
  - type: web
    name: construction-marketplace-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=400 --expose-gc --unhandled-rejections=strict
      - key: ALLOWED_ORIGINS
        value: https://construction-marketplace-1.onrender.com,https://construction-front-end.vercel.app
      - key: ALLOW_ALL_ORIGINS
        value: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 1000
      - key: ENABLE_COMPRESSION
        value: true
      - key: TRUST_PROXY
        value: true
      - key: LOG_LEVEL
        value: info
      - key: HEALTH_CHECK_INTERVAL
        value: 60000
      # Critical environment variables (set these in Render dashboard):
      # - key: MONGO_URI
      #   sync: false
      # - key: JWT_SECRET
      #   sync: false
      # - key: CLOUDINARY_URL
      #   sync: false
      # - key: CLOUDINARY_CLOUD_NAME
      #   sync: false
      # - key: CLOUDINARY_API_KEY
      #   sync: false
      # - key: CLOUDINARY_API_SECRET
      #   sync: false

  # Frontend Service
  - type: web
    name: construction-marketplace-1
    env: node
    rootDir: client
    plan: free
    buildCommand: npm ci --prefer-offline --no-audit --progress=false && NODE_OPTIONS='--max-old-space-size=1024' npm run build
    startCommand: node --max-old-space-size=400 --expose-gc server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://construction-front-end.vercel.app
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: NODE_OPTIONS
        value: --max-old-space-size=400 --expose-gc
      - key: MEMORY_PRESSURE_CHECK
        value: 1
      - key: FORCE_COLOR
        value: 0
      - key: DISABLE_PRERENDERING
        value: 1
      - key: SKIP_ENV_VALIDATION
        value: 1
